BEGIN TRANSACTION

-- 4. Insert into Jogos table
-- For Jornada 1
INSERT INTO Jogos (IdJornada, IdEquipaCasa, IdEquipaFora) VALUES
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(1, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
-- For Jornada 2
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(2, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
-- Insert fixtures for Jornada 3
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(3, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
-- Insert fixtures for Jornada 4
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(4, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
-- Insert fixtures for Jornada 5
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(5, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
-- Insert fixtures for Jornada 6
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(6, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
-- Insert fixtures for Jornada 7
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(7, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
-- Insert fixtures for Jornada 8
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(8, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
-- Insert fixtures for Jornada 9
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(9, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
-- Insert fixtures for Jornada 10
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(10, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
-- Insert fixtures for Jornada 11
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(11, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
-- Insert fixtures for Jornada 12
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(12, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
-- Insert fixtures for Jornada 13
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(13, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
-- Insert fixtures for Jornada 14
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(14, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
-- Insert fixtures for Jornada 15
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(15, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
-- Insert fixtures for Jornada 16
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(16, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
-- Insert fixtures for Jornada 17
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(17, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
-- Insert fixtures for Jornada 18
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(18, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
-- Insert fixtures for Jornada 19
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(19, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
-- Insert fixtures for Jornada 20
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(20, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
-- Insert fixtures for Jornada 21
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(21, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
-- Insert fixtures for Jornada 22
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(22, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
-- Insert fixtures for Jornada 23
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(23, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
--Insert fixtures for Jornada 24
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(24, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
--Insert fixtures for Jornada 25
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(25, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
--Insert fixtures for Jornada 26
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(26, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
--Insert fixtures for Jornada 27
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(27, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
--Insert fixtures for Jornada 28
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(28, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
--Insert fixtures for Jornada 29
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(29, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
--Insert fixtures for Jornada 30
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(30, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
--Insert fixtures for Jornada 31
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(31, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
--Insert fixtures for Jornada 32
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(32, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
--Insert fixtures for Jornada 33
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC')),
(33, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão')),
--Insert fixtures for Jornada 34
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Braga'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'SL Benfica')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Sporting CP'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Vitória SC')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Famalicão'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Casa Pia AC')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Rio Ave FC'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Gil Vicente FC')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estoril Praia'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Estrela Amadora')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Porto'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'CD Nacional')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'SC Farense'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Santa Clara')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'FC Arouca'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Boavista FC')),
(34, (SELECT IdEquipa FROM Equipas WHERE Nome = 'AVS'), (SELECT IdEquipa FROM Equipas WHERE Nome = 'Moreirense FC'));

-- Commit the transaction
COMMIT TRANSACTION;