//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaPortuguesaFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int IdJogo { get; set; }
        public int IdJornada { get; set; }
        public int IdEquipaCasa { get; set; }
        public int IdEquipaFora { get; set; }
        public int GolosCasa { get; set; }
        public int GolosFora { get; set; }
        public bool IsFinished { get; set; }
    
        public virtual Equipas Equipas { get; set; }
        public virtual Equipas Equipas1 { get; set; }
        public virtual Jornadas Jornadas { get; set; }
    }
}
